### ISSUE TITLE
ask help about SMAca software

### ISSUE THREAD

**Issue by baoyl818** [babelomics/SMAca#5]
Hi，friend

It's so kind of you to share SMAca ,which can be used in the NGS data and is open source. According to your paper I think this is a very useful tool to detect SMN1 copy number . I have test this software, but I met some problem when running **the command line**: 

smaca --profile --output ./output.csv  N2282F.recaled.bam  N2282M.recaled.bam

**The wrong message is :**
/work/Software/Anaconda3-5.1.0/lib/python3.6/site-packages/smaca/sma.py:118: RuntimeWarning: divide by zero encountered in true_divide
  self.z_ik = self.c_ix.sum(axis=1).reshape((self.n_bam, 1)) / self.H_ik
/work/Software/Anaconda3-5.1.0/lib/python3.6/site-packages/smaca/sma.py:122: RuntimeWarning: invalid value encountered in true_divide
  self.theta_i = (self.z_ik / self.zmean_k).sum(axis=1) / len(data.GENES)

I don't know where is wrong, can you help me to solve this problem ? 
Thank you very much .

**Comment by erdanieee** [comment]
Hi, It is difficult to know the exact cause without the BAMs, but it seems that either the control genes aren't covered in some of your BAM files or there is a problem with chromosomes names.  Are them WES, WGS or a custom panel?  What reference did you use?

**Comment by baoyl818** [comment]
> Hi, It is difficult to know the exact cause without the BAMs, but it seems that either the control genes aren't covered in some of your BAM files or there is a problem with chromosomes names. Are them WES, WGS or a custom panel? What reference did you use?


Dear friend, 
        My bam is WES data, and aligned to hg38. Can this software be used in the WES data ? 
Thank you for your reply.

**Comment by erdanieee** [comment]
Hi baoyl818,
we have already released a new version that supports hg38. Please, upgrade SMAca and try again with:
`smaca --reference hg38 --output output.csv N2282F.recaled.bam N2282M.recaled.bam`

Please, let me know if this works for you.
Best

**Comment by baoyl818** [comment]
Hi，erdanieee
I have tested the new SMAca pipeline, with the command line : 
`smaca --reference hg38 --output output.csv N2282F.recaled.bam N2282M.recaled.bam`
but it raise a error message : TypeError: main() got an unexpected keyword argument 'reference'.
 Then I modified two lines code of script **cli.py** (line40: ref_genome --> reference, line67: ref=ref_genome --> ref=reference) and then it works for hg38. 

Does SMAca can work for WES data ? I test two WES bam, and the result is a little confused to get the absolute number of SMN1 and SMN2 copies because we need to do some calculation based on the **cov_SMN1_p/cov_SMN2_p**,**scale_factor**. 
I have a suggestion about the output file: can the SMAca directly give the predicted number of SMN1 and SMN2 ? 

Thanks a lot.
Best

**Comment by erdanieee** [comment]
There are complex rearrangements around SMN locus that have to be manually (and carefully) inspected because they might not follows the rules we've suggested to estimate the SMN absolute copy number. Nevertheless, we're working on a machine learning approach to automate this.

On the other hand, most of the users may be only interested in classify samples as likely or non-likely carriers. In this cases, checking the Pi_x value (Pi_x<=0.33) and the two positions related to silent carriers (g.27134 =="T", g.27706_27707 == "AT") may be enough.

SMAca works fine with WGS, WES and panels as long as SMN locus and control genes are covered. The recommendation is to use the same capture kit for the whole set of samples, and analyze a large cohort at the same time. In general, the larger the set of BAMs to analyze at the same time, the easiest to interpret the results. We normally analyze batches of 30 to 300 samples.

Thank you very much for your feedback.
Best
